name: Build Python Wheels

on:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: bash scripts/install_deps_linux.sh

      - name: Build wheel
        run: bash scripts/build_wheel_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: dist/*.whl

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: powershell scripts/install_deps_windows.ps1

      - name: Build wheel
        run: powershell scripts/build_wheel_windows.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: windows-wheels
          path: dist/*.whl
